services:
  next-app:
    container_name: next-app
    build:
      context: .
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - .:/app
      - ./prisma:/app/prisma
    restart: always
    ports:
      - ${NEXT_APP_PORT}:${NEXT_APP_PORT}

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "${PMA_PORT}:${PMA_INSIDE_PORT}"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
volumes:
  mysql-data:
