services:
  next-app:
    container_name: next-app
    build:
      context: .
    env_file:
      - .env # Ensure you have production-specific environment variables here
    environment:
      DATABASE_URL: ${DATABASE_URL_NEON}
      DEBUG: false # Disable debug mode in production
    volumes:
      - .:/app
      - ./prisma:/app/prisma
      - ./public/uploads:/app/public/uploads
    restart: always
    ports:
      - "3000:3000"  # Expose the app on port 3000
