services:
  next-app:
    container_name: next-app
    build:
      context: .
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL_NEON}
      DEBUG: prisma:query
    volumes:
      - .:/app
      - ./prisma:/app/prisma
      - ./public/uploads:/app/public/uploads  # Persist uploaded images
    restart: always
    ports:
      - 3000:3000
