services:
  next-app:
    container_name: next-app
    build:
      context: .
    env_file:
      - .env # Ensure you have production-specific environment variables here
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
      DEBUG: false # Disable debug mode in production
    volumes:
      - .:/app
      - ./prisma:/app/prisma
      - ./public/uploads:/app/public/uploads
    restart: always
    ports:
      - "3000:3000"  # Expose the app on port 3000

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3

  # You can uncomment and use Redis if needed
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:
