// import { Geist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Script from "next/script";

// const geistSans = Geist({
// 	variable: "--font-geist-sans",
// 	subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
// 	variable: "--font-geist-mono",
// 	subsets: ["latin"],
// });

export const metadata = {
	title: "Go Crazy",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			{/* <body className={`${geistSans.variable} antialiased`}> */}
			<body className="relative">
				<Navbar />
				{children}
				<Script src="/js/flowbite/index.js"></Script>
			</body>
		</html>
	);
}
