import {
  ColorSchemeScript,
  mantineHtmlProps,
  MantineProvider,
} from "@mantine/core";
import "@mantine/notifications/styles.css";
import { Notifications } from "@mantine/notifications";
// import { Geist } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import Navbar from "@/components/Navbar";
import Script from "next/script";
import { theme } from "../theme";
import { ModalsProvider } from "@mantine/modals";

// const geistSans = Geist({
// 	variable: "--font-geist-sans",
// 	subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
// 	variable: "--font-geist-mono",
// 	subsets: ["latin"],
// });

export const metadata = {
  title: "Go Crazy",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
        <link rel="shortcut icon" href="/favicon.svg" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body>
        <MantineProvider withGlobalStyles withNormalizeCSS theme={theme}>
          <ModalsProvider>
            <Notifications />

            <Navbar />
            {children}
          </ModalsProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
