import {
	ColorSchemeScript,
	mantineHtmlProps,
	MantineProvider,
} from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import "./globals.css";
import "@mantine/notifications/styles.css";
import "@mantine/core/styles.css";
import Navbar from "@/components/nav/Navbar";
import { theme } from "../theme";
import { ModalsProvider } from "@mantine/modals";

export const metadata = {
	title: "Go Crazy",
	description: "Generated by create next app",
};
export default function RootLayout({ children }) {
	return (
		<html
			lang="en"
			{...mantineHtmlProps}>
			<head>
				<ColorSchemeScript />
				<link
					rel="shortcut icon"
					href="/favicon.svg"
				/>
				<meta
					name="viewport"
					content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
				/>
			</head>
			<body>
				<MantineProvider
					withGlobalStyles
					withNormalizeCSS
					theme={theme}>
					<ModalsProvider>
						<Notifications autoClose={3000} />

						<Navbar />
						{children}
					</ModalsProvider>
				</MantineProvider>
			</body>
		</html>
	);
}
