export const rolesConfig = {
	"/dashboard": ["admin", "super"],
	"/dashboard/user": ["admin", "super"],
	"/dashboard/user/create": ["super"],
	"/dashboard/user/show": ["admin", "super"],
	"/dashboard/user/edit": ["super"],
	"/dashboard/user/delete": ["super"],
	"/dashboard/post/create": ["super"],
	"/dashboard/post/show": ["admin", "super"],
	"/dashboard/post/edit": ["super"],
	"/dashboard/post/delete": ["super"],
	"/post": ["admin", "super", "member"],
	"/dashboard/user/:id": ["admin", "super"],
	"/dashboard/post/:id": ["admin", "super"],
	"/post/:id": ["admin", "super", "member"],
	"/": ["admin", "super", "member"],
};
